# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/admin/Desktop/SOCExtraFeatures/PYNQZ2_VIVADO/MotorFault_PYNQZ2.srcs/sources_1/bd/MotorFatigue_PYNQZ2/ip/MotorFatigue_PYNQZ2_axi_mem_intercon_2_imp_xbar_0/MotorFatigue_PYNQZ2_axi_mem_intercon_2_imp_xbar_0.xci
# IP: The module: 'MotorFatigue_PYNQZ2_axi_mem_intercon_2_imp_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/admin/Desktop/SOCExtraFeatures/PYNQZ2_VIVADO/MotorFault_PYNQZ2.gen/sources_1/bd/MotorFatigue_PYNQZ2/ip/MotorFatigue_PYNQZ2_axi_mem_intercon_2_imp_xbar_0/MotorFatigue_PYNQZ2_axi_mem_intercon_2_imp_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MotorFatigue_PYNQZ2_axi_mem_intercon_2_imp_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/admin/Desktop/SOCExtraFeatures/PYNQZ2_VIVADO/MotorFault_PYNQZ2.srcs/sources_1/bd/MotorFatigue_PYNQZ2/ip/MotorFatigue_PYNQZ2_axi_mem_intercon_2_imp_xbar_0/MotorFatigue_PYNQZ2_axi_mem_intercon_2_imp_xbar_0.xci
# IP: The module: 'MotorFatigue_PYNQZ2_axi_mem_intercon_2_imp_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/admin/Desktop/SOCExtraFeatures/PYNQZ2_VIVADO/MotorFault_PYNQZ2.gen/sources_1/bd/MotorFatigue_PYNQZ2/ip/MotorFatigue_PYNQZ2_axi_mem_intercon_2_imp_xbar_0/MotorFatigue_PYNQZ2_axi_mem_intercon_2_imp_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MotorFatigue_PYNQZ2_axi_mem_intercon_2_imp_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
