// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="subtract_mean_subtract_mean,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.256000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=1201,HLS_SYN_LUT=2142,HLS_VERSION=2024_2}" *)

module subtract_mean (
        ap_clk,
        ap_rst_n,
        input_stream_TDATA,
        input_stream_TVALID,
        input_stream_TREADY,
        input_stream_TKEEP,
        input_stream_TSTRB,
        input_stream_TLAST,
        output_stream_TDATA,
        output_stream_TVALID,
        output_stream_TREADY,
        output_stream_TKEEP,
        output_stream_TSTRB,
        output_stream_TLAST,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 37'd1;
parameter    ap_ST_fsm_state2 = 37'd2;
parameter    ap_ST_fsm_state3 = 37'd4;
parameter    ap_ST_fsm_state4 = 37'd8;
parameter    ap_ST_fsm_state5 = 37'd16;
parameter    ap_ST_fsm_state6 = 37'd32;
parameter    ap_ST_fsm_state7 = 37'd64;
parameter    ap_ST_fsm_state8 = 37'd128;
parameter    ap_ST_fsm_state9 = 37'd256;
parameter    ap_ST_fsm_state10 = 37'd512;
parameter    ap_ST_fsm_state11 = 37'd1024;
parameter    ap_ST_fsm_state12 = 37'd2048;
parameter    ap_ST_fsm_state13 = 37'd4096;
parameter    ap_ST_fsm_state14 = 37'd8192;
parameter    ap_ST_fsm_state15 = 37'd16384;
parameter    ap_ST_fsm_state16 = 37'd32768;
parameter    ap_ST_fsm_state17 = 37'd65536;
parameter    ap_ST_fsm_state18 = 37'd131072;
parameter    ap_ST_fsm_state19 = 37'd262144;
parameter    ap_ST_fsm_state20 = 37'd524288;
parameter    ap_ST_fsm_state21 = 37'd1048576;
parameter    ap_ST_fsm_state22 = 37'd2097152;
parameter    ap_ST_fsm_state23 = 37'd4194304;
parameter    ap_ST_fsm_state24 = 37'd8388608;
parameter    ap_ST_fsm_state25 = 37'd16777216;
parameter    ap_ST_fsm_state26 = 37'd33554432;
parameter    ap_ST_fsm_state27 = 37'd67108864;
parameter    ap_ST_fsm_state28 = 37'd134217728;
parameter    ap_ST_fsm_state29 = 37'd268435456;
parameter    ap_ST_fsm_state30 = 37'd536870912;
parameter    ap_ST_fsm_state31 = 37'd1073741824;
parameter    ap_ST_fsm_state32 = 37'd2147483648;
parameter    ap_ST_fsm_state33 = 37'd4294967296;
parameter    ap_ST_fsm_state34 = 37'd8589934592;
parameter    ap_ST_fsm_state35 = 37'd17179869184;
parameter    ap_ST_fsm_state36 = 37'd34359738368;
parameter    ap_ST_fsm_state37 = 37'd68719476736;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] input_stream_TDATA;
input   input_stream_TVALID;
output   input_stream_TREADY;
input  [3:0] input_stream_TKEEP;
input  [3:0] input_stream_TSTRB;
input  [0:0] input_stream_TLAST;
output  [31:0] output_stream_TDATA;
output   output_stream_TVALID;
input   output_stream_TREADY;
output  [3:0] output_stream_TKEEP;
output  [3:0] output_stream_TSTRB;
output  [0:0] output_stream_TLAST;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [36:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] n;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state16;
reg   [31:0] n_read_reg_433;
reg   [21:0] tmp_1_reg_447;
wire   [22:0] num_chunks_fu_281_p3;
reg   [22:0] num_chunks_reg_452;
wire    ap_CS_fsm_state2;
wire   [22:0] sub1_fu_289_p2;
reg   [22:0] sub1_reg_458;
wire   [31:0] chunk_size_fu_335_p3;
reg   [31:0] chunk_size_reg_467;
wire    ap_CS_fsm_state3;
wire   [31:0] grp_fu_197_p2;
reg   [31:0] running_sum_1_reg_482;
wire    ap_CS_fsm_state9;
wire   [31:0] grp_fu_205_p1;
reg   [31:0] conv_reg_487;
wire    ap_CS_fsm_state15;
wire   [31:0] grp_fu_201_p2;
reg   [31:0] mean_val_reg_492;
wire    ap_CS_fsm_state31;
wire   [20:0] chunk_6_fu_374_p2;
reg   [20:0] chunk_6_reg_500;
wire    ap_CS_fsm_state32;
wire   [0:0] icmp_ln44_fu_380_p2;
reg   [0:0] icmp_ln44_reg_505;
wire   [31:0] sub_ln44_fu_397_p2;
reg   [31:0] sub_ln44_reg_511;
wire   [31:0] chunk_size_1_fu_402_p3;
reg   [31:0] chunk_size_1_reg_516;
wire    ap_CS_fsm_state33;
wire   [31:0] sub63_fu_409_p2;
reg   [31:0] sub63_reg_523;
wire    ap_CS_fsm_state35;
reg   [7:0] buffer_address0;
reg    buffer_ce0;
reg    buffer_we0;
reg   [31:0] buffer_d0;
wire   [31:0] buffer_q0;
reg   [7:0] buffer_1_address0;
reg    buffer_1_ce0;
reg    buffer_1_we0;
reg   [31:0] buffer_1_d0;
wire   [31:0] buffer_1_q0;
reg   [7:0] buffer_2_address0;
reg    buffer_2_ce0;
reg    buffer_2_we0;
reg   [31:0] buffer_2_d0;
wire   [31:0] buffer_2_q0;
reg   [7:0] buffer_3_address0;
reg    buffer_3_ce0;
reg    buffer_3_we0;
reg   [31:0] buffer_3_d0;
wire   [31:0] buffer_3_q0;
wire    grp_subtract_mean_Pipeline_read_chunk_fu_142_ap_start;
wire    grp_subtract_mean_Pipeline_read_chunk_fu_142_ap_done;
wire    grp_subtract_mean_Pipeline_read_chunk_fu_142_ap_idle;
wire    grp_subtract_mean_Pipeline_read_chunk_fu_142_ap_ready;
wire   [7:0] grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_3_address0;
wire    grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_3_ce0;
wire    grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_3_we0;
wire   [31:0] grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_3_d0;
wire   [7:0] grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_2_address0;
wire    grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_2_ce0;
wire    grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_2_we0;
wire   [31:0] grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_2_d0;
wire   [7:0] grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_1_address0;
wire    grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_1_ce0;
wire    grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_1_we0;
wire   [31:0] grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_1_d0;
wire   [7:0] grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_r_address0;
wire    grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_r_ce0;
wire    grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_r_we0;
wire   [31:0] grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_r_d0;
wire    grp_subtract_mean_Pipeline_read_chunk_fu_142_input_stream_TREADY;
wire   [31:0] grp_subtract_mean_Pipeline_read_chunk_fu_142_chunk_sum_out;
wire    grp_subtract_mean_Pipeline_read_chunk_fu_142_chunk_sum_out_ap_vld;
wire   [31:0] grp_subtract_mean_Pipeline_read_chunk_fu_142_grp_fu_197_p_din0;
wire   [31:0] grp_subtract_mean_Pipeline_read_chunk_fu_142_grp_fu_197_p_din1;
wire   [0:0] grp_subtract_mean_Pipeline_read_chunk_fu_142_grp_fu_197_p_opcode;
wire    grp_subtract_mean_Pipeline_read_chunk_fu_142_grp_fu_197_p_ce;
wire    grp_subtract_mean_Pipeline_read_for_subtract_fu_160_ap_start;
wire    grp_subtract_mean_Pipeline_read_for_subtract_fu_160_ap_done;
wire    grp_subtract_mean_Pipeline_read_for_subtract_fu_160_ap_idle;
wire    grp_subtract_mean_Pipeline_read_for_subtract_fu_160_ap_ready;
wire   [7:0] grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_3_address0;
wire    grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_3_ce0;
wire    grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_3_we0;
wire   [31:0] grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_3_d0;
wire   [7:0] grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_2_address0;
wire    grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_2_ce0;
wire    grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_2_we0;
wire   [31:0] grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_2_d0;
wire   [7:0] grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_1_address0;
wire    grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_1_ce0;
wire    grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_1_we0;
wire   [31:0] grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_1_d0;
wire   [7:0] grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_r_address0;
wire    grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_r_ce0;
wire    grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_r_we0;
wire   [31:0] grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_r_d0;
wire    grp_subtract_mean_Pipeline_read_for_subtract_fu_160_input_stream_TREADY;
wire    grp_subtract_mean_Pipeline_write_result_fu_177_ap_start;
wire    grp_subtract_mean_Pipeline_write_result_fu_177_ap_done;
wire    grp_subtract_mean_Pipeline_write_result_fu_177_ap_idle;
wire    grp_subtract_mean_Pipeline_write_result_fu_177_ap_ready;
wire    grp_subtract_mean_Pipeline_write_result_fu_177_output_stream_TREADY;
wire   [7:0] grp_subtract_mean_Pipeline_write_result_fu_177_buffer_r_address0;
wire    grp_subtract_mean_Pipeline_write_result_fu_177_buffer_r_ce0;
wire   [7:0] grp_subtract_mean_Pipeline_write_result_fu_177_buffer_1_address0;
wire    grp_subtract_mean_Pipeline_write_result_fu_177_buffer_1_ce0;
wire   [7:0] grp_subtract_mean_Pipeline_write_result_fu_177_buffer_2_address0;
wire    grp_subtract_mean_Pipeline_write_result_fu_177_buffer_2_ce0;
wire   [7:0] grp_subtract_mean_Pipeline_write_result_fu_177_buffer_3_address0;
wire    grp_subtract_mean_Pipeline_write_result_fu_177_buffer_3_ce0;
wire   [31:0] grp_subtract_mean_Pipeline_write_result_fu_177_output_stream_TDATA;
wire    grp_subtract_mean_Pipeline_write_result_fu_177_output_stream_TVALID;
wire   [3:0] grp_subtract_mean_Pipeline_write_result_fu_177_output_stream_TKEEP;
wire   [3:0] grp_subtract_mean_Pipeline_write_result_fu_177_output_stream_TSTRB;
wire   [0:0] grp_subtract_mean_Pipeline_write_result_fu_177_output_stream_TLAST;
wire   [31:0] grp_subtract_mean_Pipeline_write_result_fu_177_grp_fu_197_p_din0;
wire   [31:0] grp_subtract_mean_Pipeline_write_result_fu_177_grp_fu_197_p_din1;
wire   [0:0] grp_subtract_mean_Pipeline_write_result_fu_177_grp_fu_197_p_opcode;
wire    grp_subtract_mean_Pipeline_write_result_fu_177_grp_fu_197_p_ce;
reg    grp_subtract_mean_Pipeline_read_chunk_fu_142_ap_start_reg;
wire   [0:0] icmp_ln21_fu_302_p2;
wire    ap_CS_fsm_state4;
reg    grp_subtract_mean_Pipeline_read_for_subtract_fu_160_ap_start_reg;
wire    ap_CS_fsm_state34;
reg    grp_subtract_mean_Pipeline_write_result_fu_177_ap_start_reg;
wire    ap_CS_fsm_state36;
reg   [31:0] output_stream_TDATA_reg;
reg   [3:0] output_stream_TKEEP_reg;
reg   [3:0] output_stream_TSTRB_reg;
reg   [0:0] output_stream_TLAST_reg;
reg   [20:0] chunk_fu_104;
wire   [20:0] chunk_4_fu_307_p2;
reg   [31:0] running_sum_fu_108;
wire    ap_CS_fsm_state10;
reg   [20:0] chunk_2_fu_132;
reg   [31:0] grp_fu_197_p0;
reg   [31:0] grp_fu_197_p1;
wire   [31:0] sub_ln18_fu_219_p2;
wire   [31:0] add_ln18_fu_245_p2;
wire   [22:0] zext_ln18_fu_258_p1;
wire   [21:0] tmp_2_fu_267_p4;
wire   [0:0] tmp_fu_250_p3;
wire   [22:0] sub_ln18_1_fu_261_p2;
wire   [22:0] zext_ln18_1_fu_277_p1;
wire   [22:0] zext_ln21_fu_298_p1;
wire   [30:0] shl_ln_fu_318_p3;
wire   [31:0] zext_ln22_fu_326_p1;
wire   [0:0] icmp_ln22_fu_313_p2;
wire   [31:0] sub_ln22_fu_330_p2;
wire   [22:0] zext_ln43_fu_365_p1;
wire   [30:0] shl_ln1_fu_385_p3;
wire   [31:0] zext_ln44_fu_393_p1;
reg   [1:0] grp_fu_197_opcode;
reg    grp_fu_197_ce;
wire   [0:0] icmp_ln43_fu_369_p2;
wire    ap_CS_fsm_state37;
wire    regslice_both_output_stream_V_data_V_U_apdone_blk;
reg   [36:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
reg    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
reg    ap_ST_fsm_state36_blk;
reg    ap_ST_fsm_state37_blk;
wire    regslice_both_input_stream_V_data_V_U_apdone_blk;
wire   [31:0] input_stream_TDATA_int_regslice;
wire    input_stream_TVALID_int_regslice;
reg    input_stream_TREADY_int_regslice;
wire    regslice_both_input_stream_V_data_V_U_ack_in;
wire    regslice_both_input_stream_V_keep_V_U_apdone_blk;
wire   [3:0] input_stream_TKEEP_int_regslice;
wire    regslice_both_input_stream_V_keep_V_U_vld_out;
wire    regslice_both_input_stream_V_keep_V_U_ack_in;
wire    regslice_both_input_stream_V_strb_V_U_apdone_blk;
wire   [3:0] input_stream_TSTRB_int_regslice;
wire    regslice_both_input_stream_V_strb_V_U_vld_out;
wire    regslice_both_input_stream_V_strb_V_U_ack_in;
wire    regslice_both_input_stream_V_last_V_U_apdone_blk;
wire   [0:0] input_stream_TLAST_int_regslice;
wire    regslice_both_input_stream_V_last_V_U_vld_out;
wire    regslice_both_input_stream_V_last_V_U_ack_in;
reg   [31:0] output_stream_TDATA_int_regslice;
wire    output_stream_TVALID_int_regslice;
wire    output_stream_TREADY_int_regslice;
wire    regslice_both_output_stream_V_data_V_U_vld_out;
wire    regslice_both_output_stream_V_keep_V_U_apdone_blk;
reg   [3:0] output_stream_TKEEP_int_regslice;
wire    regslice_both_output_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_output_stream_V_keep_V_U_vld_out;
wire    regslice_both_output_stream_V_strb_V_U_apdone_blk;
reg   [3:0] output_stream_TSTRB_int_regslice;
wire    regslice_both_output_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_output_stream_V_strb_V_U_vld_out;
wire    regslice_both_output_stream_V_last_V_U_apdone_blk;
reg   [0:0] output_stream_TLAST_int_regslice;
wire    regslice_both_output_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_output_stream_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 37'd1;
#0 grp_subtract_mean_Pipeline_read_chunk_fu_142_ap_start_reg = 1'b0;
#0 grp_subtract_mean_Pipeline_read_for_subtract_fu_160_ap_start_reg = 1'b0;
#0 grp_subtract_mean_Pipeline_write_result_fu_177_ap_start_reg = 1'b0;
#0 chunk_fu_104 = 21'd0;
#0 running_sum_fu_108 = 32'd0;
#0 chunk_2_fu_132 = 21'd0;
end

subtract_mean_buffer_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
buffer_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(buffer_address0),
    .ce0(buffer_ce0),
    .we0(buffer_we0),
    .d0(buffer_d0),
    .q0(buffer_q0)
);

subtract_mean_buffer_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
buffer_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(buffer_1_address0),
    .ce0(buffer_1_ce0),
    .we0(buffer_1_we0),
    .d0(buffer_1_d0),
    .q0(buffer_1_q0)
);

subtract_mean_buffer_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
buffer_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(buffer_2_address0),
    .ce0(buffer_2_ce0),
    .we0(buffer_2_we0),
    .d0(buffer_2_d0),
    .q0(buffer_2_q0)
);

subtract_mean_buffer_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
buffer_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(buffer_3_address0),
    .ce0(buffer_3_ce0),
    .we0(buffer_3_we0),
    .d0(buffer_3_d0),
    .q0(buffer_3_q0)
);

subtract_mean_subtract_mean_Pipeline_read_chunk grp_subtract_mean_Pipeline_read_chunk_fu_142(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_subtract_mean_Pipeline_read_chunk_fu_142_ap_start),
    .ap_done(grp_subtract_mean_Pipeline_read_chunk_fu_142_ap_done),
    .ap_idle(grp_subtract_mean_Pipeline_read_chunk_fu_142_ap_idle),
    .ap_ready(grp_subtract_mean_Pipeline_read_chunk_fu_142_ap_ready),
    .input_stream_TVALID(input_stream_TVALID_int_regslice),
    .chunk_size(chunk_size_reg_467),
    .buffer_3_address0(grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_3_address0),
    .buffer_3_ce0(grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_3_ce0),
    .buffer_3_we0(grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_3_we0),
    .buffer_3_d0(grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_3_d0),
    .buffer_2_address0(grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_2_address0),
    .buffer_2_ce0(grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_2_ce0),
    .buffer_2_we0(grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_2_we0),
    .buffer_2_d0(grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_2_d0),
    .buffer_1_address0(grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_1_address0),
    .buffer_1_ce0(grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_1_ce0),
    .buffer_1_we0(grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_1_we0),
    .buffer_1_d0(grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_1_d0),
    .buffer_r_address0(grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_r_address0),
    .buffer_r_ce0(grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_r_ce0),
    .buffer_r_we0(grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_r_we0),
    .buffer_r_d0(grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_r_d0),
    .input_stream_TDATA(input_stream_TDATA_int_regslice),
    .input_stream_TREADY(grp_subtract_mean_Pipeline_read_chunk_fu_142_input_stream_TREADY),
    .input_stream_TKEEP(input_stream_TKEEP_int_regslice),
    .input_stream_TSTRB(input_stream_TSTRB_int_regslice),
    .input_stream_TLAST(input_stream_TLAST_int_regslice),
    .chunk_sum_out(grp_subtract_mean_Pipeline_read_chunk_fu_142_chunk_sum_out),
    .chunk_sum_out_ap_vld(grp_subtract_mean_Pipeline_read_chunk_fu_142_chunk_sum_out_ap_vld),
    .grp_fu_197_p_din0(grp_subtract_mean_Pipeline_read_chunk_fu_142_grp_fu_197_p_din0),
    .grp_fu_197_p_din1(grp_subtract_mean_Pipeline_read_chunk_fu_142_grp_fu_197_p_din1),
    .grp_fu_197_p_opcode(grp_subtract_mean_Pipeline_read_chunk_fu_142_grp_fu_197_p_opcode),
    .grp_fu_197_p_dout0(grp_fu_197_p2),
    .grp_fu_197_p_ce(grp_subtract_mean_Pipeline_read_chunk_fu_142_grp_fu_197_p_ce)
);

subtract_mean_subtract_mean_Pipeline_read_for_subtract grp_subtract_mean_Pipeline_read_for_subtract_fu_160(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_subtract_mean_Pipeline_read_for_subtract_fu_160_ap_start),
    .ap_done(grp_subtract_mean_Pipeline_read_for_subtract_fu_160_ap_done),
    .ap_idle(grp_subtract_mean_Pipeline_read_for_subtract_fu_160_ap_idle),
    .ap_ready(grp_subtract_mean_Pipeline_read_for_subtract_fu_160_ap_ready),
    .input_stream_TVALID(input_stream_TVALID_int_regslice),
    .chunk_size_1(chunk_size_1_reg_516),
    .buffer_3_address0(grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_3_address0),
    .buffer_3_ce0(grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_3_ce0),
    .buffer_3_we0(grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_3_we0),
    .buffer_3_d0(grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_3_d0),
    .buffer_2_address0(grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_2_address0),
    .buffer_2_ce0(grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_2_ce0),
    .buffer_2_we0(grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_2_we0),
    .buffer_2_d0(grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_2_d0),
    .buffer_1_address0(grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_1_address0),
    .buffer_1_ce0(grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_1_ce0),
    .buffer_1_we0(grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_1_we0),
    .buffer_1_d0(grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_1_d0),
    .buffer_r_address0(grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_r_address0),
    .buffer_r_ce0(grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_r_ce0),
    .buffer_r_we0(grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_r_we0),
    .buffer_r_d0(grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_r_d0),
    .input_stream_TDATA(input_stream_TDATA_int_regslice),
    .input_stream_TREADY(grp_subtract_mean_Pipeline_read_for_subtract_fu_160_input_stream_TREADY),
    .input_stream_TKEEP(input_stream_TKEEP_int_regslice),
    .input_stream_TSTRB(input_stream_TSTRB_int_regslice),
    .input_stream_TLAST(input_stream_TLAST_int_regslice)
);

subtract_mean_subtract_mean_Pipeline_write_result grp_subtract_mean_Pipeline_write_result_fu_177(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_subtract_mean_Pipeline_write_result_fu_177_ap_start),
    .ap_done(grp_subtract_mean_Pipeline_write_result_fu_177_ap_done),
    .ap_idle(grp_subtract_mean_Pipeline_write_result_fu_177_ap_idle),
    .ap_ready(grp_subtract_mean_Pipeline_write_result_fu_177_ap_ready),
    .output_stream_TREADY(grp_subtract_mean_Pipeline_write_result_fu_177_output_stream_TREADY),
    .chunk_size_1(chunk_size_1_reg_516),
    .buffer_r_address0(grp_subtract_mean_Pipeline_write_result_fu_177_buffer_r_address0),
    .buffer_r_ce0(grp_subtract_mean_Pipeline_write_result_fu_177_buffer_r_ce0),
    .buffer_r_q0(buffer_q0),
    .buffer_1_address0(grp_subtract_mean_Pipeline_write_result_fu_177_buffer_1_address0),
    .buffer_1_ce0(grp_subtract_mean_Pipeline_write_result_fu_177_buffer_1_ce0),
    .buffer_1_q0(buffer_1_q0),
    .buffer_2_address0(grp_subtract_mean_Pipeline_write_result_fu_177_buffer_2_address0),
    .buffer_2_ce0(grp_subtract_mean_Pipeline_write_result_fu_177_buffer_2_ce0),
    .buffer_2_q0(buffer_2_q0),
    .buffer_3_address0(grp_subtract_mean_Pipeline_write_result_fu_177_buffer_3_address0),
    .buffer_3_ce0(grp_subtract_mean_Pipeline_write_result_fu_177_buffer_3_ce0),
    .buffer_3_q0(buffer_3_q0),
    .mean_val(mean_val_reg_492),
    .sub63(sub63_reg_523),
    .icmp_ln44(icmp_ln44_reg_505),
    .output_stream_TDATA(grp_subtract_mean_Pipeline_write_result_fu_177_output_stream_TDATA),
    .output_stream_TVALID(grp_subtract_mean_Pipeline_write_result_fu_177_output_stream_TVALID),
    .output_stream_TKEEP(grp_subtract_mean_Pipeline_write_result_fu_177_output_stream_TKEEP),
    .output_stream_TSTRB(grp_subtract_mean_Pipeline_write_result_fu_177_output_stream_TSTRB),
    .output_stream_TLAST(grp_subtract_mean_Pipeline_write_result_fu_177_output_stream_TLAST),
    .grp_fu_197_p_din0(grp_subtract_mean_Pipeline_write_result_fu_177_grp_fu_197_p_din0),
    .grp_fu_197_p_din1(grp_subtract_mean_Pipeline_write_result_fu_177_grp_fu_197_p_din1),
    .grp_fu_197_p_opcode(grp_subtract_mean_Pipeline_write_result_fu_177_grp_fu_197_p_opcode),
    .grp_fu_197_p_dout0(grp_fu_197_p2),
    .grp_fu_197_p_ce(grp_subtract_mean_Pipeline_write_result_fu_177_grp_fu_197_p_ce)
);

subtract_mean_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .n(n),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

subtract_mean_faddfsub_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
faddfsub_32ns_32ns_32_5_full_dsp_1_U36(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_197_p0),
    .din1(grp_fu_197_p1),
    .opcode(grp_fu_197_opcode),
    .ce(grp_fu_197_ce),
    .dout(grp_fu_197_p2)
);

subtract_mean_fdiv_32ns_32ns_32_16_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 16 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_16_no_dsp_1_U37(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(running_sum_fu_108),
    .din1(conv_reg_487),
    .ce(1'b1),
    .dout(grp_fu_201_p2)
);

subtract_mean_sitofp_32ns_32_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32ns_32_6_no_dsp_1_U38(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(n_read_reg_433),
    .ce(1'b1),
    .dout(grp_fu_205_p1)
);

subtract_mean_regslice_both #(
    .DataWidth( 32 ))
regslice_both_input_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream_TDATA),
    .vld_in(input_stream_TVALID),
    .ack_in(regslice_both_input_stream_V_data_V_U_ack_in),
    .data_out(input_stream_TDATA_int_regslice),
    .vld_out(input_stream_TVALID_int_regslice),
    .ack_out(input_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream_V_data_V_U_apdone_blk)
);

subtract_mean_regslice_both #(
    .DataWidth( 4 ))
regslice_both_input_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream_TKEEP),
    .vld_in(input_stream_TVALID),
    .ack_in(regslice_both_input_stream_V_keep_V_U_ack_in),
    .data_out(input_stream_TKEEP_int_regslice),
    .vld_out(regslice_both_input_stream_V_keep_V_U_vld_out),
    .ack_out(input_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream_V_keep_V_U_apdone_blk)
);

subtract_mean_regslice_both #(
    .DataWidth( 4 ))
regslice_both_input_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream_TSTRB),
    .vld_in(input_stream_TVALID),
    .ack_in(regslice_both_input_stream_V_strb_V_U_ack_in),
    .data_out(input_stream_TSTRB_int_regslice),
    .vld_out(regslice_both_input_stream_V_strb_V_U_vld_out),
    .ack_out(input_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream_V_strb_V_U_apdone_blk)
);

subtract_mean_regslice_both #(
    .DataWidth( 1 ))
regslice_both_input_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream_TLAST),
    .vld_in(input_stream_TVALID),
    .ack_in(regslice_both_input_stream_V_last_V_U_ack_in),
    .data_out(input_stream_TLAST_int_regslice),
    .vld_out(regslice_both_input_stream_V_last_V_U_vld_out),
    .ack_out(input_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream_V_last_V_U_apdone_blk)
);

subtract_mean_regslice_both #(
    .DataWidth( 32 ))
regslice_both_output_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output_stream_TDATA_int_regslice),
    .vld_in(grp_subtract_mean_Pipeline_write_result_fu_177_output_stream_TVALID),
    .ack_in(output_stream_TREADY_int_regslice),
    .data_out(output_stream_TDATA),
    .vld_out(regslice_both_output_stream_V_data_V_U_vld_out),
    .ack_out(output_stream_TREADY),
    .apdone_blk(regslice_both_output_stream_V_data_V_U_apdone_blk)
);

subtract_mean_regslice_both #(
    .DataWidth( 4 ))
regslice_both_output_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output_stream_TKEEP_int_regslice),
    .vld_in(grp_subtract_mean_Pipeline_write_result_fu_177_output_stream_TVALID),
    .ack_in(regslice_both_output_stream_V_keep_V_U_ack_in_dummy),
    .data_out(output_stream_TKEEP),
    .vld_out(regslice_both_output_stream_V_keep_V_U_vld_out),
    .ack_out(output_stream_TREADY),
    .apdone_blk(regslice_both_output_stream_V_keep_V_U_apdone_blk)
);

subtract_mean_regslice_both #(
    .DataWidth( 4 ))
regslice_both_output_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output_stream_TSTRB_int_regslice),
    .vld_in(grp_subtract_mean_Pipeline_write_result_fu_177_output_stream_TVALID),
    .ack_in(regslice_both_output_stream_V_strb_V_U_ack_in_dummy),
    .data_out(output_stream_TSTRB),
    .vld_out(regslice_both_output_stream_V_strb_V_U_vld_out),
    .ack_out(output_stream_TREADY),
    .apdone_blk(regslice_both_output_stream_V_strb_V_U_apdone_blk)
);

subtract_mean_regslice_both #(
    .DataWidth( 1 ))
regslice_both_output_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output_stream_TLAST_int_regslice),
    .vld_in(grp_subtract_mean_Pipeline_write_result_fu_177_output_stream_TVALID),
    .ack_in(regslice_both_output_stream_V_last_V_U_ack_in_dummy),
    .data_out(output_stream_TLAST),
    .vld_out(regslice_both_output_stream_V_last_V_U_vld_out),
    .ack_out(output_stream_TREADY),
    .apdone_blk(regslice_both_output_stream_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_subtract_mean_Pipeline_read_chunk_fu_142_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln21_fu_302_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_subtract_mean_Pipeline_read_chunk_fu_142_ap_start_reg <= 1'b1;
        end else if ((grp_subtract_mean_Pipeline_read_chunk_fu_142_ap_ready == 1'b1)) begin
            grp_subtract_mean_Pipeline_read_chunk_fu_142_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_subtract_mean_Pipeline_read_for_subtract_fu_160_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state33)) begin
            grp_subtract_mean_Pipeline_read_for_subtract_fu_160_ap_start_reg <= 1'b1;
        end else if ((grp_subtract_mean_Pipeline_read_for_subtract_fu_160_ap_ready == 1'b1)) begin
            grp_subtract_mean_Pipeline_read_for_subtract_fu_160_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_subtract_mean_Pipeline_write_result_fu_177_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state35)) begin
            grp_subtract_mean_Pipeline_write_result_fu_177_ap_start_reg <= 1'b1;
        end else if ((grp_subtract_mean_Pipeline_write_result_fu_177_ap_ready == 1'b1)) begin
            grp_subtract_mean_Pipeline_write_result_fu_177_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_302_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        chunk_2_fu_132 <= 21'd0;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        chunk_2_fu_132 <= chunk_6_reg_500;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        chunk_fu_104 <= 21'd0;
    end else if (((icmp_ln21_fu_302_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        chunk_fu_104 <= chunk_4_fu_307_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        running_sum_fu_108 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        running_sum_fu_108 <= running_sum_1_reg_482;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        chunk_6_reg_500 <= chunk_6_fu_374_p2;
        icmp_ln44_reg_505 <= icmp_ln44_fu_380_p2;
        sub_ln44_reg_511 <= sub_ln44_fu_397_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        chunk_size_1_reg_516 <= chunk_size_1_fu_402_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        chunk_size_reg_467 <= chunk_size_fu_335_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        conv_reg_487 <= grp_fu_205_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        mean_val_reg_492 <= grp_fu_201_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        n_read_reg_433 <= n;
        tmp_1_reg_447 <= {{sub_ln18_fu_219_p2[31:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        num_chunks_reg_452 <= num_chunks_fu_281_p3;
        sub1_reg_458 <= sub1_fu_289_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_subtract_mean_Pipeline_write_result_fu_177_output_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state36))) begin
        output_stream_TDATA_reg <= grp_subtract_mean_Pipeline_write_result_fu_177_output_stream_TDATA;
        output_stream_TKEEP_reg <= grp_subtract_mean_Pipeline_write_result_fu_177_output_stream_TKEEP;
        output_stream_TLAST_reg <= grp_subtract_mean_Pipeline_write_result_fu_177_output_stream_TLAST;
        output_stream_TSTRB_reg <= grp_subtract_mean_Pipeline_write_result_fu_177_output_stream_TSTRB;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        running_sum_1_reg_482 <= grp_fu_197_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state35)) begin
        sub63_reg_523 <= sub63_fu_409_p2;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

always @ (*) begin
    if ((grp_subtract_mean_Pipeline_read_for_subtract_fu_160_ap_done == 1'b0)) begin
        ap_ST_fsm_state34_blk = 1'b1;
    end else begin
        ap_ST_fsm_state34_blk = 1'b0;
    end
end

assign ap_ST_fsm_state35_blk = 1'b0;

always @ (*) begin
    if ((grp_subtract_mean_Pipeline_write_result_fu_177_ap_done == 1'b0)) begin
        ap_ST_fsm_state36_blk = 1'b1;
    end else begin
        ap_ST_fsm_state36_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_output_stream_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state37_blk = 1'b1;
    end else begin
        ap_ST_fsm_state37_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_subtract_mean_Pipeline_read_chunk_fu_142_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((regslice_both_output_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state37))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_output_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state37))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        buffer_1_address0 = grp_subtract_mean_Pipeline_write_result_fu_177_buffer_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state34)) begin
        buffer_1_address0 = grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buffer_1_address0 = grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_1_address0;
    end else begin
        buffer_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        buffer_1_ce0 = grp_subtract_mean_Pipeline_write_result_fu_177_buffer_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state34)) begin
        buffer_1_ce0 = grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buffer_1_ce0 = grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_1_ce0;
    end else begin
        buffer_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        buffer_1_d0 = grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buffer_1_d0 = grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_1_d0;
    end else begin
        buffer_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        buffer_1_we0 = grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buffer_1_we0 = grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_1_we0;
    end else begin
        buffer_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        buffer_2_address0 = grp_subtract_mean_Pipeline_write_result_fu_177_buffer_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state34)) begin
        buffer_2_address0 = grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buffer_2_address0 = grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_2_address0;
    end else begin
        buffer_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        buffer_2_ce0 = grp_subtract_mean_Pipeline_write_result_fu_177_buffer_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state34)) begin
        buffer_2_ce0 = grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buffer_2_ce0 = grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_2_ce0;
    end else begin
        buffer_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        buffer_2_d0 = grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_2_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buffer_2_d0 = grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_2_d0;
    end else begin
        buffer_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        buffer_2_we0 = grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_2_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buffer_2_we0 = grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_2_we0;
    end else begin
        buffer_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        buffer_3_address0 = grp_subtract_mean_Pipeline_write_result_fu_177_buffer_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state34)) begin
        buffer_3_address0 = grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buffer_3_address0 = grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_3_address0;
    end else begin
        buffer_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        buffer_3_ce0 = grp_subtract_mean_Pipeline_write_result_fu_177_buffer_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state34)) begin
        buffer_3_ce0 = grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buffer_3_ce0 = grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_3_ce0;
    end else begin
        buffer_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        buffer_3_d0 = grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_3_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buffer_3_d0 = grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_3_d0;
    end else begin
        buffer_3_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        buffer_3_we0 = grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_3_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buffer_3_we0 = grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_3_we0;
    end else begin
        buffer_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        buffer_address0 = grp_subtract_mean_Pipeline_write_result_fu_177_buffer_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state34)) begin
        buffer_address0 = grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buffer_address0 = grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_r_address0;
    end else begin
        buffer_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        buffer_ce0 = grp_subtract_mean_Pipeline_write_result_fu_177_buffer_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state34)) begin
        buffer_ce0 = grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buffer_ce0 = grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_r_ce0;
    end else begin
        buffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        buffer_d0 = grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_r_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buffer_d0 = grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_r_d0;
    end else begin
        buffer_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        buffer_we0 = grp_subtract_mean_Pipeline_read_for_subtract_fu_160_buffer_r_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buffer_we0 = grp_subtract_mean_Pipeline_read_chunk_fu_142_buffer_r_we0;
    end else begin
        buffer_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        grp_fu_197_ce = grp_subtract_mean_Pipeline_write_result_fu_177_grp_fu_197_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_197_ce = grp_subtract_mean_Pipeline_read_chunk_fu_142_grp_fu_197_p_ce;
    end else begin
        grp_fu_197_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        grp_fu_197_opcode = grp_subtract_mean_Pipeline_write_result_fu_177_grp_fu_197_p_opcode;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_197_opcode = grp_subtract_mean_Pipeline_read_chunk_fu_142_grp_fu_197_p_opcode;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_197_opcode = 2'd0;
    end else begin
        grp_fu_197_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        grp_fu_197_p0 = grp_subtract_mean_Pipeline_write_result_fu_177_grp_fu_197_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_197_p0 = grp_subtract_mean_Pipeline_read_chunk_fu_142_grp_fu_197_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_197_p0 = running_sum_fu_108;
    end else begin
        grp_fu_197_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        grp_fu_197_p1 = grp_subtract_mean_Pipeline_write_result_fu_177_grp_fu_197_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_197_p1 = grp_subtract_mean_Pipeline_read_chunk_fu_142_grp_fu_197_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_197_p1 = grp_subtract_mean_Pipeline_read_chunk_fu_142_chunk_sum_out;
    end else begin
        grp_fu_197_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        input_stream_TREADY_int_regslice = grp_subtract_mean_Pipeline_read_for_subtract_fu_160_input_stream_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        input_stream_TREADY_int_regslice = grp_subtract_mean_Pipeline_read_chunk_fu_142_input_stream_TREADY;
    end else begin
        input_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((grp_subtract_mean_Pipeline_write_result_fu_177_output_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state36))) begin
        output_stream_TDATA_int_regslice = grp_subtract_mean_Pipeline_write_result_fu_177_output_stream_TDATA;
    end else begin
        output_stream_TDATA_int_regslice = output_stream_TDATA_reg;
    end
end

always @ (*) begin
    if (((grp_subtract_mean_Pipeline_write_result_fu_177_output_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state36))) begin
        output_stream_TKEEP_int_regslice = grp_subtract_mean_Pipeline_write_result_fu_177_output_stream_TKEEP;
    end else begin
        output_stream_TKEEP_int_regslice = output_stream_TKEEP_reg;
    end
end

always @ (*) begin
    if (((grp_subtract_mean_Pipeline_write_result_fu_177_output_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state36))) begin
        output_stream_TLAST_int_regslice = grp_subtract_mean_Pipeline_write_result_fu_177_output_stream_TLAST;
    end else begin
        output_stream_TLAST_int_regslice = output_stream_TLAST_reg;
    end
end

always @ (*) begin
    if (((grp_subtract_mean_Pipeline_write_result_fu_177_output_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state36))) begin
        output_stream_TSTRB_int_regslice = grp_subtract_mean_Pipeline_write_result_fu_177_output_stream_TSTRB;
    end else begin
        output_stream_TSTRB_int_regslice = output_stream_TSTRB_reg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln21_fu_302_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_subtract_mean_Pipeline_read_chunk_fu_142_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            if (((icmp_ln43_fu_369_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state32))) begin
                ap_NS_fsm = ap_ST_fsm_state37;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            if (((grp_subtract_mean_Pipeline_read_for_subtract_fu_160_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state34))) begin
                ap_NS_fsm = ap_ST_fsm_state35;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state34;
            end
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            if (((grp_subtract_mean_Pipeline_write_result_fu_177_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state36))) begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state36;
            end
        end
        ap_ST_fsm_state37 : begin
            if (((regslice_both_output_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state37))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state37;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln18_fu_245_p2 = (n_read_reg_433 + 32'd1023);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign chunk_4_fu_307_p2 = (chunk_fu_104 + 21'd1);

assign chunk_6_fu_374_p2 = (chunk_2_fu_132 + 21'd1);

assign chunk_size_1_fu_402_p3 = ((icmp_ln44_reg_505[0:0] == 1'b1) ? sub_ln44_reg_511 : 32'd1024);

assign chunk_size_fu_335_p3 = ((icmp_ln22_fu_313_p2[0:0] == 1'b1) ? sub_ln22_fu_330_p2 : 32'd1024);

assign grp_subtract_mean_Pipeline_read_chunk_fu_142_ap_start = grp_subtract_mean_Pipeline_read_chunk_fu_142_ap_start_reg;

assign grp_subtract_mean_Pipeline_read_for_subtract_fu_160_ap_start = grp_subtract_mean_Pipeline_read_for_subtract_fu_160_ap_start_reg;

assign grp_subtract_mean_Pipeline_write_result_fu_177_ap_start = grp_subtract_mean_Pipeline_write_result_fu_177_ap_start_reg;

assign grp_subtract_mean_Pipeline_write_result_fu_177_output_stream_TREADY = (output_stream_TREADY_int_regslice & ap_CS_fsm_state36);

assign icmp_ln21_fu_302_p2 = (($signed(zext_ln21_fu_298_p1) < $signed(num_chunks_reg_452)) ? 1'b1 : 1'b0);

assign icmp_ln22_fu_313_p2 = ((zext_ln21_fu_298_p1 == sub1_reg_458) ? 1'b1 : 1'b0);

assign icmp_ln43_fu_369_p2 = (($signed(zext_ln43_fu_365_p1) < $signed(num_chunks_reg_452)) ? 1'b1 : 1'b0);

assign icmp_ln44_fu_380_p2 = ((zext_ln43_fu_365_p1 == sub1_reg_458) ? 1'b1 : 1'b0);

assign input_stream_TREADY = regslice_both_input_stream_V_data_V_U_ack_in;

assign num_chunks_fu_281_p3 = ((tmp_fu_250_p3[0:0] == 1'b1) ? sub_ln18_1_fu_261_p2 : zext_ln18_1_fu_277_p1);

assign output_stream_TVALID = regslice_both_output_stream_V_data_V_U_vld_out;

assign output_stream_TVALID_int_regslice = grp_subtract_mean_Pipeline_write_result_fu_177_output_stream_TVALID;

assign shl_ln1_fu_385_p3 = {{chunk_2_fu_132}, {10'd0}};

assign shl_ln_fu_318_p3 = {{chunk_fu_104}, {10'd0}};

assign sub1_fu_289_p2 = ($signed(num_chunks_fu_281_p3) + $signed(23'd8388607));

assign sub63_fu_409_p2 = ($signed(chunk_size_1_reg_516) + $signed(32'd4294967295));

assign sub_ln18_1_fu_261_p2 = (23'd0 - zext_ln18_fu_258_p1);

assign sub_ln18_fu_219_p2 = ($signed(32'd4294966273) - $signed(n));

assign sub_ln22_fu_330_p2 = (n_read_reg_433 - zext_ln22_fu_326_p1);

assign sub_ln44_fu_397_p2 = (n_read_reg_433 - zext_ln44_fu_393_p1);

assign tmp_2_fu_267_p4 = {{add_ln18_fu_245_p2[31:10]}};

assign tmp_fu_250_p3 = add_ln18_fu_245_p2[32'd31];

assign zext_ln18_1_fu_277_p1 = tmp_2_fu_267_p4;

assign zext_ln18_fu_258_p1 = tmp_1_reg_447;

assign zext_ln21_fu_298_p1 = chunk_fu_104;

assign zext_ln22_fu_326_p1 = shl_ln_fu_318_p3;

assign zext_ln43_fu_365_p1 = chunk_2_fu_132;

assign zext_ln44_fu_393_p1 = shl_ln1_fu_385_p3;


reg find_kernel_block = 0;
// synthesis translate_off
`include "subtract_mean_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //subtract_mean

