// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="complex_mag_stream_complex_mag_stream,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.282800,HLS_SYN_LAT=21474836497,HLS_SYN_TPT=none,HLS_SYN_MEM=14,HLS_SYN_DSP=0,HLS_SYN_FF=9640,HLS_SYN_LUT=6969,HLS_VERSION=2024_2}" *)

module complex_mag_stream (
        ap_clk,
        ap_rst_n,
        input_stream_id_TDATA,
        input_stream_id_TVALID,
        input_stream_id_TREADY,
        input_stream_iq_TDATA,
        input_stream_iq_TVALID,
        input_stream_iq_TREADY,
        output_stream_TDATA,
        output_stream_TVALID,
        output_stream_TREADY,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 44'd1;
parameter    ap_ST_fsm_state2 = 44'd2;
parameter    ap_ST_fsm_state3 = 44'd4;
parameter    ap_ST_fsm_state4 = 44'd8;
parameter    ap_ST_fsm_state5 = 44'd16;
parameter    ap_ST_fsm_state6 = 44'd32;
parameter    ap_ST_fsm_state7 = 44'd64;
parameter    ap_ST_fsm_state8 = 44'd128;
parameter    ap_ST_fsm_state9 = 44'd256;
parameter    ap_ST_fsm_state10 = 44'd512;
parameter    ap_ST_fsm_state11 = 44'd1024;
parameter    ap_ST_fsm_state12 = 44'd2048;
parameter    ap_ST_fsm_state13 = 44'd4096;
parameter    ap_ST_fsm_state14 = 44'd8192;
parameter    ap_ST_fsm_state15 = 44'd16384;
parameter    ap_ST_fsm_state16 = 44'd32768;
parameter    ap_ST_fsm_state17 = 44'd65536;
parameter    ap_ST_fsm_state18 = 44'd131072;
parameter    ap_ST_fsm_state19 = 44'd262144;
parameter    ap_ST_fsm_state20 = 44'd524288;
parameter    ap_ST_fsm_state21 = 44'd1048576;
parameter    ap_ST_fsm_state22 = 44'd2097152;
parameter    ap_ST_fsm_state23 = 44'd4194304;
parameter    ap_ST_fsm_state24 = 44'd8388608;
parameter    ap_ST_fsm_state25 = 44'd16777216;
parameter    ap_ST_fsm_state26 = 44'd33554432;
parameter    ap_ST_fsm_state27 = 44'd67108864;
parameter    ap_ST_fsm_state28 = 44'd134217728;
parameter    ap_ST_fsm_state29 = 44'd268435456;
parameter    ap_ST_fsm_state30 = 44'd536870912;
parameter    ap_ST_fsm_state31 = 44'd1073741824;
parameter    ap_ST_fsm_state32 = 44'd2147483648;
parameter    ap_ST_fsm_state33 = 44'd4294967296;
parameter    ap_ST_fsm_state34 = 44'd8589934592;
parameter    ap_ST_fsm_state35 = 44'd17179869184;
parameter    ap_ST_fsm_state36 = 44'd34359738368;
parameter    ap_ST_fsm_state37 = 44'd68719476736;
parameter    ap_ST_fsm_state38 = 44'd137438953472;
parameter    ap_ST_fsm_state39 = 44'd274877906944;
parameter    ap_ST_fsm_state40 = 44'd549755813888;
parameter    ap_ST_fsm_state41 = 44'd1099511627776;
parameter    ap_ST_fsm_state42 = 44'd2199023255552;
parameter    ap_ST_fsm_state43 = 44'd4398046511104;
parameter    ap_ST_fsm_state44 = 44'd8796093022208;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [95:0] input_stream_id_TDATA;
input   input_stream_id_TVALID;
output   input_stream_id_TREADY;
input  [95:0] input_stream_iq_TDATA;
input   input_stream_iq_TVALID;
output   input_stream_iq_TREADY;
output  [95:0] output_stream_TDATA;
output   output_stream_TVALID;
input   output_stream_TREADY;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [43:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] n;
reg    input_stream_id_TDATA_blk_n;
wire    ap_CS_fsm_state39;
reg    input_stream_iq_TDATA_blk_n;
reg    output_stream_TDATA_blk_n;
wire    ap_CS_fsm_state43;
wire    ap_CS_fsm_state44;
wire  signed [31:0] add_ln126_fu_239_p2;
reg  signed [31:0] add_ln126_reg_561;
reg   [0:0] tmp_15_reg_566;
wire    ap_CS_fsm_state2;
wire   [64:0] grp_fu_234_p2;
reg   [64:0] mul_ln126_reg_577;
wire    ap_CS_fsm_state3;
reg   [29:0] tmp_21_cast_reg_582;
wire   [29:0] select_ln126_fu_293_p3;
reg   [29:0] select_ln126_reg_587;
wire    ap_CS_fsm_state4;
wire   [2:0] grp_fu_253_p2;
reg   [2:0] srem_ln127_reg_592;
wire    ap_CS_fsm_state36;
wire   [30:0] select_ln126_1_fu_308_p3;
reg   [30:0] select_ln126_1_reg_597;
wire    ap_CS_fsm_state37;
wire   [2:0] last_block_size_fu_324_p3;
reg   [2:0] last_block_size_reg_602;
wire   [30:0] sub3_fu_332_p2;
reg   [30:0] sub3_reg_608;
wire   [0:0] cmp24_fu_338_p2;
reg   [0:0] cmp24_reg_613;
wire   [2:0] select_ln152_fu_350_p3;
reg   [2:0] select_ln152_reg_618;
wire   [29:0] blk_count_2_fu_370_p2;
reg   [29:0] blk_count_2_reg_626;
wire    ap_CS_fsm_state38;
wire   [0:0] icmp_ln136_fu_376_p2;
reg   [0:0] icmp_ln136_reg_631;
wire   [31:0] id_blk_fu_385_p1;
reg   [31:0] id_blk_reg_637;
wire   [31:0] id_blk_1_fu_398_p1;
reg   [31:0] id_blk_1_reg_642;
wire   [31:0] id_blk_2_fu_411_p1;
reg   [31:0] id_blk_2_reg_647;
wire   [31:0] iq_blk_fu_420_p1;
reg   [31:0] iq_blk_reg_652;
wire   [31:0] iq_blk_1_fu_433_p1;
reg   [31:0] iq_blk_1_reg_657;
wire   [31:0] iq_blk_2_fu_446_p1;
reg   [31:0] iq_blk_2_reg_662;
wire   [2:0] elements_in_block_fu_451_p3;
reg   [2:0] elements_in_block_reg_667;
wire   [0:0] and_ln151_fu_458_p2;
reg   [0:0] and_ln151_reg_672;
wire    grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194_ap_start;
wire    grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194_ap_done;
wire    grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194_ap_idle;
wire    grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194_ap_ready;
wire   [31:0] grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194_out_blk_0_2_load52_out;
wire    grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194_out_blk_0_2_load52_out_ap_vld;
wire   [31:0] grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194_out_blk_0_1_load45_out;
wire    grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194_out_blk_0_1_load45_out_ap_vld;
wire   [31:0] grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194_out_blk_0_0_load38_out;
wire    grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194_out_blk_0_0_load38_out_ap_vld;
wire    grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222_ap_start;
wire    grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222_ap_done;
wire    grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222_ap_idle;
wire    grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222_ap_ready;
wire   [31:0] grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222_out_blk_0_2_load48_out;
wire    grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222_out_blk_0_2_load48_out_ap_vld;
wire   [31:0] grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222_out_blk_0_1_load41_out;
wire    grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222_out_blk_0_1_load41_out_ap_vld;
wire   [31:0] grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222_out_blk_0_0_load34_out;
wire    grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222_out_blk_0_0_load34_out_ap_vld;
reg   [31:0] ap_phi_mux_out_blk_0_2_load_phi_fu_170_p4;
reg   [31:0] out_blk_0_2_load_reg_167;
wire    ap_CS_fsm_state41;
reg   [31:0] ap_phi_mux_out_blk_0_1_load_phi_fu_179_p4;
reg   [31:0] out_blk_0_1_load_reg_176;
reg   [31:0] ap_phi_mux_out_blk_0_0_load_phi_fu_188_p4;
reg   [31:0] out_blk_0_0_load_reg_185;
reg    grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194_ap_start_reg;
reg    ap_block_state39_ignore_call18;
wire    ap_CS_fsm_state40;
reg    grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222_ap_start_reg;
wire    ap_CS_fsm_state42;
reg   [29:0] blk_count_fu_114;
reg    ap_block_state39;
wire   [33:0] grp_fu_234_p1;
wire   [2:0] grp_fu_253_p1;
wire   [64:0] sub_ln126_fu_278_p2;
wire   [29:0] tmp_20_cast_fu_283_p4;
wire   [30:0] zext_ln126_fu_299_p1;
wire   [30:0] sub_ln126_1_fu_302_p2;
wire   [2:0] trunc_ln127_fu_315_p1;
wire   [0:0] icmp_ln127_fu_318_p2;
wire   [2:0] add_ln152_fu_344_p2;
wire   [30:0] zext_ln129_fu_361_p1;
wire   [31:0] trunc_ln131_fu_381_p1;
wire   [31:0] tmp_fu_390_p3;
wire   [31:0] tmp_s_fu_403_p3;
wire   [31:0] trunc_ln132_fu_416_p1;
wire   [31:0] tmp_1_fu_425_p3;
wire   [31:0] tmp_2_fu_438_p3;
wire   [31:0] bitcast_ln158_2_fu_494_p1;
wire   [31:0] bitcast_ln158_1_fu_490_p1;
wire   [31:0] bitcast_ln158_fu_486_p1;
reg    grp_fu_253_ap_start;
wire    grp_fu_253_ap_done;
wire   [0:0] icmp_ln129_fu_365_p2;
wire    regslice_both_output_stream_U_apdone_blk;
reg   [43:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
reg    ap_ST_fsm_state38_blk;
reg    ap_ST_fsm_state39_blk;
reg    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
reg    ap_ST_fsm_state42_blk;
reg    ap_ST_fsm_state43_blk;
reg    ap_ST_fsm_state44_blk;
wire    regslice_both_input_stream_id_U_apdone_blk;
wire   [95:0] input_stream_id_TDATA_int_regslice;
wire    input_stream_id_TVALID_int_regslice;
reg    input_stream_id_TREADY_int_regslice;
wire    regslice_both_input_stream_id_U_ack_in;
wire    regslice_both_input_stream_iq_U_apdone_blk;
wire   [95:0] input_stream_iq_TDATA_int_regslice;
wire    input_stream_iq_TVALID_int_regslice;
reg    input_stream_iq_TREADY_int_regslice;
wire    regslice_both_input_stream_iq_U_ack_in;
wire   [95:0] output_stream_TDATA_int_regslice;
reg    output_stream_TVALID_int_regslice;
wire    output_stream_TREADY_int_regslice;
wire    regslice_both_output_stream_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 44'd1;
#0 grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194_ap_start_reg = 1'b0;
#0 grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222_ap_start_reg = 1'b0;
#0 blk_count_fu_114 = 30'd0;
end

complex_mag_stream_complex_mag_stream_Pipeline_VITIS_LOOP_139_2 grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194_ap_start),
    .ap_done(grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194_ap_done),
    .ap_idle(grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194_ap_idle),
    .ap_ready(grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194_ap_ready),
    .elements_in_block(elements_in_block_reg_667),
    .id_blk_3(id_blk_reg_637),
    .id_blk_4(id_blk_1_reg_642),
    .id_blk_5(id_blk_2_reg_647),
    .iq_blk_3(iq_blk_reg_652),
    .iq_blk_4(iq_blk_1_reg_657),
    .iq_blk_5(iq_blk_2_reg_662),
    .out_blk_0_2_load52_out(grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194_out_blk_0_2_load52_out),
    .out_blk_0_2_load52_out_ap_vld(grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194_out_blk_0_2_load52_out_ap_vld),
    .out_blk_0_1_load45_out(grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194_out_blk_0_1_load45_out),
    .out_blk_0_1_load45_out_ap_vld(grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194_out_blk_0_1_load45_out_ap_vld),
    .out_blk_0_0_load38_out(grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194_out_blk_0_0_load38_out),
    .out_blk_0_0_load38_out_ap_vld(grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194_out_blk_0_0_load38_out_ap_vld)
);

complex_mag_stream_complex_mag_stream_Pipeline_VITIS_LOOP_152_3 grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222_ap_start),
    .ap_done(grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222_ap_done),
    .ap_idle(grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222_ap_idle),
    .ap_ready(grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222_ap_ready),
    .out_blk_0_2_load52_reload(grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194_out_blk_0_2_load52_out),
    .out_blk_0_1_load45_reload(grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194_out_blk_0_1_load45_out),
    .out_blk_0_0_load38_reload(grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194_out_blk_0_0_load38_out),
    .last_block_size(last_block_size_reg_602),
    .zext_ln129(select_ln152_reg_618),
    .out_blk_0_2_load48_out(grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222_out_blk_0_2_load48_out),
    .out_blk_0_2_load48_out_ap_vld(grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222_out_blk_0_2_load48_out_ap_vld),
    .out_blk_0_1_load41_out(grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222_out_blk_0_1_load41_out),
    .out_blk_0_1_load41_out_ap_vld(grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222_out_blk_0_1_load41_out_ap_vld),
    .out_blk_0_0_load34_out(grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222_out_blk_0_0_load34_out),
    .out_blk_0_0_load34_out_ap_vld(grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222_out_blk_0_0_load34_out_ap_vld)
);

complex_mag_stream_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .n(n),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

complex_mag_stream_mul_32s_34ns_65_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 65 ))
mul_32s_34ns_65_2_1_U54(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(add_ln126_reg_561),
    .din1(grp_fu_234_p1),
    .ce(1'b1),
    .dout(grp_fu_234_p2)
);

complex_mag_stream_srem_32ns_3ns_3_36_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
srem_32ns_3ns_3_36_seq_1_U55(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .start(grp_fu_253_ap_start),
    .done(grp_fu_253_ap_done),
    .din0(n),
    .din1(grp_fu_253_p1),
    .ce(1'b1),
    .dout(grp_fu_253_p2)
);

complex_mag_stream_regslice_both #(
    .DataWidth( 96 ))
regslice_both_input_stream_id_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream_id_TDATA),
    .vld_in(input_stream_id_TVALID),
    .ack_in(regslice_both_input_stream_id_U_ack_in),
    .data_out(input_stream_id_TDATA_int_regslice),
    .vld_out(input_stream_id_TVALID_int_regslice),
    .ack_out(input_stream_id_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream_id_U_apdone_blk)
);

complex_mag_stream_regslice_both #(
    .DataWidth( 96 ))
regslice_both_input_stream_iq_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream_iq_TDATA),
    .vld_in(input_stream_iq_TVALID),
    .ack_in(regslice_both_input_stream_iq_U_ack_in),
    .data_out(input_stream_iq_TDATA_int_regslice),
    .vld_out(input_stream_iq_TVALID_int_regslice),
    .ack_out(input_stream_iq_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream_iq_U_apdone_blk)
);

complex_mag_stream_regslice_both #(
    .DataWidth( 96 ))
regslice_both_output_stream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output_stream_TDATA_int_regslice),
    .vld_in(output_stream_TVALID_int_regslice),
    .ack_in(output_stream_TREADY_int_regslice),
    .data_out(output_stream_TDATA),
    .vld_out(regslice_both_output_stream_U_vld_out),
    .ack_out(output_stream_TREADY),
    .apdone_blk(regslice_both_output_stream_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state39_ignore_call18) & (1'b1 == ap_CS_fsm_state39))) begin
            grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194_ap_start_reg <= 1'b1;
        end else if ((grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194_ap_ready == 1'b1)) begin
            grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222_ap_start_reg <= 1'b0;
    end else begin
        if (((1'd1 == and_ln151_reg_672) & (1'b1 == ap_CS_fsm_state41))) begin
            grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222_ap_start_reg <= 1'b1;
        end else if ((grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222_ap_ready == 1'b1)) begin
            grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        blk_count_fu_114 <= 30'd0;
    end else if (((output_stream_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state43))) begin
        blk_count_fu_114 <= blk_count_2_reg_626;
    end
end

always @ (posedge ap_clk) begin
    if (((output_stream_TREADY_int_regslice == 1'b1) & (1'd1 == and_ln151_reg_672) & (1'b1 == ap_CS_fsm_state43))) begin
        out_blk_0_0_load_reg_185 <= grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222_out_blk_0_0_load34_out;
    end else if (((1'd0 == and_ln151_reg_672) & (1'b1 == ap_CS_fsm_state41))) begin
        out_blk_0_0_load_reg_185 <= grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194_out_blk_0_0_load38_out;
    end
end

always @ (posedge ap_clk) begin
    if (((output_stream_TREADY_int_regslice == 1'b1) & (1'd1 == and_ln151_reg_672) & (1'b1 == ap_CS_fsm_state43))) begin
        out_blk_0_1_load_reg_176 <= grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222_out_blk_0_1_load41_out;
    end else if (((1'd0 == and_ln151_reg_672) & (1'b1 == ap_CS_fsm_state41))) begin
        out_blk_0_1_load_reg_176 <= grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194_out_blk_0_1_load45_out;
    end
end

always @ (posedge ap_clk) begin
    if (((output_stream_TREADY_int_regslice == 1'b1) & (1'd1 == and_ln151_reg_672) & (1'b1 == ap_CS_fsm_state43))) begin
        out_blk_0_2_load_reg_167 <= grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222_out_blk_0_2_load48_out;
    end else if (((1'd0 == and_ln151_reg_672) & (1'b1 == ap_CS_fsm_state41))) begin
        out_blk_0_2_load_reg_167 <= grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194_out_blk_0_2_load52_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        add_ln126_reg_561 <= add_ln126_fu_239_p2;
        tmp_15_reg_566 <= add_ln126_fu_239_p2[32'd31];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state39)) begin
        and_ln151_reg_672 <= and_ln151_fu_458_p2;
        elements_in_block_reg_667 <= elements_in_block_fu_451_p3;
        id_blk_1_reg_642 <= id_blk_1_fu_398_p1;
        id_blk_2_reg_647 <= id_blk_2_fu_411_p1;
        id_blk_reg_637 <= id_blk_fu_385_p1;
        iq_blk_1_reg_657 <= iq_blk_1_fu_433_p1;
        iq_blk_2_reg_662 <= iq_blk_2_fu_446_p1;
        iq_blk_reg_652 <= iq_blk_fu_420_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        blk_count_2_reg_626 <= blk_count_2_fu_370_p2;
        icmp_ln136_reg_631 <= icmp_ln136_fu_376_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        cmp24_reg_613 <= cmp24_fu_338_p2;
        last_block_size_reg_602 <= last_block_size_fu_324_p3;
        select_ln126_1_reg_597 <= select_ln126_1_fu_308_p3;
        select_ln152_reg_618 <= select_ln152_fu_350_p3;
        sub3_reg_608 <= sub3_fu_332_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        mul_ln126_reg_577 <= grp_fu_234_p2;
        tmp_21_cast_reg_582 <= {{grp_fu_234_p2[63:34]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        select_ln126_reg_587 <= select_ln126_fu_293_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        srem_ln127_reg_592 <= grp_fu_253_p2;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

always @ (*) begin
    if ((regslice_both_output_stream_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state38_blk = 1'b1;
    end else begin
        ap_ST_fsm_state38_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state39)) begin
        ap_ST_fsm_state39_blk = 1'b1;
    end else begin
        ap_ST_fsm_state39_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194_ap_done == 1'b0)) begin
        ap_ST_fsm_state40_blk = 1'b1;
    end else begin
        ap_ST_fsm_state40_blk = 1'b0;
    end
end

assign ap_ST_fsm_state41_blk = 1'b0;

always @ (*) begin
    if ((grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222_ap_done == 1'b0)) begin
        ap_ST_fsm_state42_blk = 1'b1;
    end else begin
        ap_ST_fsm_state42_blk = 1'b0;
    end
end

always @ (*) begin
    if ((output_stream_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state43_blk = 1'b1;
    end else begin
        ap_ST_fsm_state43_blk = 1'b0;
    end
end

always @ (*) begin
    if ((output_stream_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state44_blk = 1'b1;
    end else begin
        ap_ST_fsm_state44_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((regslice_both_output_stream_U_apdone_blk == 1'b0) & (icmp_ln129_fu_365_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state38))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln151_reg_672) & (1'b1 == ap_CS_fsm_state43))) begin
        ap_phi_mux_out_blk_0_0_load_phi_fu_188_p4 = grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222_out_blk_0_0_load34_out;
    end else begin
        ap_phi_mux_out_blk_0_0_load_phi_fu_188_p4 = out_blk_0_0_load_reg_185;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln151_reg_672) & (1'b1 == ap_CS_fsm_state43))) begin
        ap_phi_mux_out_blk_0_1_load_phi_fu_179_p4 = grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222_out_blk_0_1_load41_out;
    end else begin
        ap_phi_mux_out_blk_0_1_load_phi_fu_179_p4 = out_blk_0_1_load_reg_176;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln151_reg_672) & (1'b1 == ap_CS_fsm_state43))) begin
        ap_phi_mux_out_blk_0_2_load_phi_fu_170_p4 = grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222_out_blk_0_2_load48_out;
    end else begin
        ap_phi_mux_out_blk_0_2_load_phi_fu_170_p4 = out_blk_0_2_load_reg_167;
    end
end

always @ (*) begin
    if (((regslice_both_output_stream_U_apdone_blk == 1'b0) & (icmp_ln129_fu_365_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state38))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        grp_fu_253_ap_start = 1'b1;
    end else begin
        grp_fu_253_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state39)) begin
        input_stream_id_TDATA_blk_n = input_stream_id_TVALID_int_regslice;
    end else begin
        input_stream_id_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state39) & (1'b1 == ap_CS_fsm_state39))) begin
        input_stream_id_TREADY_int_regslice = 1'b1;
    end else begin
        input_stream_id_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state39)) begin
        input_stream_iq_TDATA_blk_n = input_stream_iq_TVALID_int_regslice;
    end else begin
        input_stream_iq_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state39) & (1'b1 == ap_CS_fsm_state39))) begin
        input_stream_iq_TREADY_int_regslice = 1'b1;
    end else begin
        input_stream_iq_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state43))) begin
        output_stream_TDATA_blk_n = output_stream_TREADY_int_regslice;
    end else begin
        output_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((output_stream_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state43))) begin
        output_stream_TVALID_int_regslice = 1'b1;
    end else begin
        output_stream_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            if (((regslice_both_output_stream_U_apdone_blk == 1'b0) & (icmp_ln129_fu_365_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state38))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((regslice_both_output_stream_U_apdone_blk == 1'b0) & (icmp_ln129_fu_365_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state38))) begin
                ap_NS_fsm = ap_ST_fsm_state39;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state38;
            end
        end
        ap_ST_fsm_state39 : begin
            if (((1'b0 == ap_block_state39) & (1'b1 == ap_CS_fsm_state39))) begin
                ap_NS_fsm = ap_ST_fsm_state40;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state39;
            end
        end
        ap_ST_fsm_state40 : begin
            if (((1'b1 == ap_CS_fsm_state40) & (grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state41;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state40;
            end
        end
        ap_ST_fsm_state41 : begin
            if (((1'd0 == and_ln151_reg_672) & (1'b1 == ap_CS_fsm_state41))) begin
                ap_NS_fsm = ap_ST_fsm_state43;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state42;
            end
        end
        ap_ST_fsm_state42 : begin
            if (((1'b1 == ap_CS_fsm_state42) & (grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state43;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state42;
            end
        end
        ap_ST_fsm_state43 : begin
            if (((output_stream_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state43))) begin
                ap_NS_fsm = ap_ST_fsm_state44;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state43;
            end
        end
        ap_ST_fsm_state44 : begin
            if (((output_stream_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state44))) begin
                ap_NS_fsm = ap_ST_fsm_state38;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state44;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln126_fu_239_p2 = (n + 32'd2);

assign add_ln152_fu_344_p2 = (last_block_size_fu_324_p3 + 3'd1);

assign and_ln151_fu_458_p2 = (icmp_ln136_reg_631 & cmp24_reg_613);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state40 = ap_CS_fsm[32'd39];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd41];

assign ap_CS_fsm_state43 = ap_CS_fsm[32'd42];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

always @ (*) begin
    ap_block_state39 = ((input_stream_iq_TVALID_int_regslice == 1'b0) | (input_stream_id_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state39_ignore_call18 = ((input_stream_iq_TVALID_int_regslice == 1'b0) | (input_stream_id_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign bitcast_ln158_1_fu_490_p1 = ap_phi_mux_out_blk_0_1_load_phi_fu_179_p4;

assign bitcast_ln158_2_fu_494_p1 = ap_phi_mux_out_blk_0_2_load_phi_fu_170_p4;

assign bitcast_ln158_fu_486_p1 = ap_phi_mux_out_blk_0_0_load_phi_fu_188_p4;

assign blk_count_2_fu_370_p2 = (blk_count_fu_114 + 30'd1);

assign cmp24_fu_338_p2 = ((last_block_size_fu_324_p3 != 3'd3) ? 1'b1 : 1'b0);

assign elements_in_block_fu_451_p3 = ((icmp_ln136_reg_631[0:0] == 1'b1) ? last_block_size_reg_602 : 3'd3);

assign grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194_ap_start = grp_complex_mag_stream_Pipeline_VITIS_LOOP_139_2_fu_194_ap_start_reg;

assign grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222_ap_start = grp_complex_mag_stream_Pipeline_VITIS_LOOP_152_3_fu_222_ap_start_reg;

assign grp_fu_234_p1 = 65'd5726623062;

assign grp_fu_253_p1 = 32'd3;

assign icmp_ln127_fu_318_p2 = ((trunc_ln127_fu_315_p1 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln129_fu_365_p2 = (($signed(zext_ln129_fu_361_p1) < $signed(select_ln126_1_reg_597)) ? 1'b1 : 1'b0);

assign icmp_ln136_fu_376_p2 = ((zext_ln129_fu_361_p1 == sub3_reg_608) ? 1'b1 : 1'b0);

assign id_blk_1_fu_398_p1 = tmp_fu_390_p3;

assign id_blk_2_fu_411_p1 = tmp_s_fu_403_p3;

assign id_blk_fu_385_p1 = trunc_ln131_fu_381_p1;

assign input_stream_id_TREADY = regslice_both_input_stream_id_U_ack_in;

assign input_stream_iq_TREADY = regslice_both_input_stream_iq_U_ack_in;

assign iq_blk_1_fu_433_p1 = tmp_1_fu_425_p3;

assign iq_blk_2_fu_446_p1 = tmp_2_fu_438_p3;

assign iq_blk_fu_420_p1 = trunc_ln132_fu_416_p1;

assign last_block_size_fu_324_p3 = ((icmp_ln127_fu_318_p2[0:0] == 1'b1) ? 3'd3 : trunc_ln127_fu_315_p1);

assign output_stream_TDATA_int_regslice = {{{bitcast_ln158_2_fu_494_p1}, {bitcast_ln158_1_fu_490_p1}}, {bitcast_ln158_fu_486_p1}};

assign output_stream_TVALID = regslice_both_output_stream_U_vld_out;

assign select_ln126_1_fu_308_p3 = ((tmp_15_reg_566[0:0] == 1'b1) ? sub_ln126_1_fu_302_p2 : zext_ln126_fu_299_p1);

assign select_ln126_fu_293_p3 = ((tmp_15_reg_566[0:0] == 1'b1) ? tmp_20_cast_fu_283_p4 : tmp_21_cast_reg_582);

assign select_ln152_fu_350_p3 = ((cmp24_fu_338_p2[0:0] == 1'b1) ? 3'd3 : add_ln152_fu_344_p2);

assign sub3_fu_332_p2 = ($signed(select_ln126_1_fu_308_p3) + $signed(31'd2147483647));

assign sub_ln126_1_fu_302_p2 = (31'd0 - zext_ln126_fu_299_p1);

assign sub_ln126_fu_278_p2 = (65'd0 - mul_ln126_reg_577);

assign tmp_1_fu_425_p3 = {{input_stream_iq_TDATA_int_regslice[63:32]}};

assign tmp_20_cast_fu_283_p4 = {{sub_ln126_fu_278_p2[63:34]}};

assign tmp_2_fu_438_p3 = {{input_stream_iq_TDATA_int_regslice[95:64]}};

assign tmp_fu_390_p3 = {{input_stream_id_TDATA_int_regslice[63:32]}};

assign tmp_s_fu_403_p3 = {{input_stream_id_TDATA_int_regslice[95:64]}};

assign trunc_ln127_fu_315_p1 = srem_ln127_reg_592[2:0];

assign trunc_ln131_fu_381_p1 = input_stream_id_TDATA_int_regslice[31:0];

assign trunc_ln132_fu_416_p1 = input_stream_iq_TDATA_int_regslice[31:0];

assign zext_ln126_fu_299_p1 = select_ln126_reg_587;

assign zext_ln129_fu_361_p1 = blk_count_fu_114;


reg find_kernel_block = 0;
// synthesis translate_off
`include "complex_mag_stream_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //complex_mag_stream

