#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("float_stream_TREADY", 1, hls_in, 1, "axis", "out_acc", 1),
	Port_Property("blk_stream_TDATA", 96, hls_in, 0, "axis", "in_data", 1),
	Port_Property("blk_stream_TVALID", 1, hls_in, 0, "axis", "in_vld", 1),
	Port_Property("blk_stream_TREADY", 1, hls_out, 0, "axis", "in_acc", 1),
	Port_Property("float_stream_TDATA", 32, hls_out, 1, "axis", "out_data", 1),
	Port_Property("float_stream_TVALID", 1, hls_out, 5, "axis", "out_vld", 1),
	Port_Property("float_stream_TKEEP", 4, hls_out, 2, "axis", "out_data", 1),
	Port_Property("float_stream_TSTRB", 4, hls_out, 3, "axis", "out_data", 1),
	Port_Property("float_stream_TUSER", 32, hls_out, 4, "axis", "out_data", 1),
	Port_Property("float_stream_TLAST", 1, hls_out, 5, "axis", "out_data", 1),
	Port_Property("s_axi_CTRL_AWVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_AWREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CTRL_AWADDR", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_WVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_WREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CTRL_WDATA", 32, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_WSTRB", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_ARVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_ARREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CTRL_ARADDR", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_RVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CTRL_RREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_RDATA", 32, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CTRL_RRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("interrupt", 1, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "unpack_blk_to_stream";
